# General settings
title: CTB3330 - Structural Mechanics 4
author: Tom van Woudenberg

html:
  baseurl :  "https://oit.tudelft.nl/CTB3330/2025/intro.html"
  home_page_in_navbar       : true

only_build_toc_files: true

# Execute notebooks when building
execute:
  execute_notebooks: 'off'

sphinx:
  config:
    html_show_copyright: false
    html_static_path: ["figures"] # add folders that contain files that need to be included, such as the location of the logo(s)
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/**"]
    html_theme_options:
      logo:
        text: CTB3330 - Structural Mechanics 4 2025/2026
      repository_url: "https://github.com/TUDelft-books/CTB3330" #add your own repo URL here
      path_to_docs: "book"
      repository_branch: "2025"
      use_edit_page_button: true
      use_repository_button: true
      use_issues_button : true
      git_show_all_authors: true
      launch_buttons:
        thebe: true
  extra_extensions:
    - sphinx.ext.imgconverter
    - sphinx.ext.extlinks
    - teachbooks_favourites
    - sphinx_tudelft_theme
    - sphinx_apa_references
    
bibtex_bibfiles: 
  - references.bib
