###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Tom van Woudenberg'
bibtex_bibfiles = ['references.bib']
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2023'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'teachbooks_favourites', 'sphinx_tudelft_theme', 'sphinx_apa_references', 'teachbooks_questions', 'sphinxcontrib.bibtex', 'sphinx_jupyterbook_latex', 'sphinx_multitoc_numbering']
external_toc_exclude_missing = True
external_toc_path = '_toc.yml'
git_show_all_authors = False
html_baseurl = 'https://oit.tudelft.nl/CTB3330/2025/intro.html'
html_css_files = ['center-grid.css', 'remove_author.css']
html_favicon = ''
html_js_files = ['https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js']
html_logo = ''
html_show_copyright = False
html_sourcelink_suffix = ''
html_static_path = ['figures', '_static']
html_theme = 'sphinx_book_theme'
html_theme_options = {'logo': {'text': 'CTB3330 - Structural Mechanics 4 2025/2026'}, 'repository_url': 'https://github.com/TUDelft-books/CTB3330', 'path_to_docs': 'book', 'repository_branch': '2025-teacher', 'use_edit_page_button': True, 'use_repository_button': True, 'use_issues_button': True, 'launch_buttons': {'thebe': True}}
html_title = 'CTB3330 - Structural Mechanics 4'
latex_engine = 'pdflatex'
myst_enable_extensions = ['colon_fence', 'dollarmath', 'linkify', 'substitution', 'tasklist']
myst_url_schemes = ['mailto', 'http', 'https']
nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = 'off'
nb_execution_timeout = 30
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
thebe_config = {'use_thebe_lite': True, 'exclude_patterns': ['**/**']}
tud_change_titlesize = False
use_jupyterbook_latex = True
use_multitoc_numbering = True
